version: '1'

services:
  app:
    image: python_git
    command: python3 /home/scrap_in_docker_container/main.py
    container_name: python_git_container
    #volumes:
    #  - ./:/home
    # La bandera -i le indica a docker utilizar el STDIN del contenedor.
    # La bandera -t indica que se requiere de una pseudo terminal.
    stdin_open: true
    tty: true
